/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CaseCard: typeof import('./src/components/common/CaseCard.vue')['default']
    CaseSection: typeof import('./src/components/sections/CaseSection.vue')['default']
    CTASection: typeof import('./src/components/sections/CTASection.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    FeatureCard: typeof import('./src/components/common/FeatureCard.vue')['default']
    FeatureSection: typeof import('./src/components/sections/FeatureSection.vue')['default']
    FooterSection: typeof import('./src/components/sections/FooterSection.vue')['default']
    HeroSection: typeof import('./src/components/sections/HeroSection.vue')['default']
    LoginModal: typeof import('./src/components/common/LoginModal.vue')['default']
    NavbarSection: typeof import('./src/components/sections/NavbarSection.vue')['default']
    NewsModal: typeof import('./src/components/common/NewsModal.vue')['default']
    NewsModule: typeof import('./src/components/common/NewsModule.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneCard: typeof import('./src/components/common/SceneCard.vue')['default']
    SceneSection: typeof import('./src/components/sections/SceneSection.vue')['default']
    ValueCard: typeof import('./src/components/common/ValueCard.vue')['default']
    ValueSection: typeof import('./src/components/sections/ValueSection.vue')['default']
  }
}
