version: "3.8"

# 测试环境
# 通过 BRAND_ID 环境变量指定品牌：xingkou | xiading

services:
  frontend:
    image: ar-home:latest
    ports:
      - "8777:80"
    environment:
      - BRAND_ID=xiading
    restart: unless-stopped
